name: Ext - Build, Lint, and Test

on:
  pull_request:
    paths:
      - extension-src/**
      - .github/workflows/ext-blt.yml
  workflow_call:

jobs:
  blt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install
        working-directory: extension-src
        run: bun install --frozen-lockfile

      - name: Lint
        working-directory: extension-src
        run: bun run lint

      - name: Test
        working-directory: extension-src
        run: bun test

      - name: Build
        working-directory: extension-src
        run: bun run build
