name: Ext - Build, Lint, and Test

on:
  pull_request:
    paths:
      - pkg/extension/**
      - pkg/common/**
      - .github/workflows/ext-blt.yml
  workflow_call:

jobs:
  ext-blt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install
        working-directory: pkg/extension
        run: bun install --frozen-lockfile

      - name: Lint
        working-directory: pkg/extension
        run: bun run lint

      - name: Test
        working-directory: pkg/extension
        run: bun test

      - name: Build
        working-directory: pkg/extension
        run: bun run build
